export const products = [
  {
    id: '1',
    name: 'Beetlejuice Boots',
    img: '/img/beetlejuiceBoots.jpg',
    price: '290',
    description: 'Best boots for a gothic party',
  },
  {
    id: '2',
    name: 'Black Cat Shoes',
    img: '/img/blackCatShoes.jpg',
    price: 250,
    description: 'Your everyday shoe!',
  },
  {
    id: '3',
    name: 'Bring it on Boots',
    img: '/img/Bring-it-on!-Boots.jpg',
    price: 300,
    description: 'Unique shoes, the toughest boots!',
  },
  {
    id: '4',
    name: 'Cant Escape Platform sandals',
    img: '/img/Can_t-escape-platform-shoes.jpg',
    price: 220,
    description: 'Beautiful platform sandals',
  },
  {
    id: '5',
    name: 'Chunky Trainers',
    img: '/img/Chunky-Trainers.jpg',
    price: 210,
    description: "The coolest sports you'l ever get",
  },
  {
    id: '6',
    name: 'Dark Combat',
    img: '/img/Dark-Combat-BOOTS.jpg',
    price: 280,
    description: 'Elegant tall boots',
  },
  {
    id: '7',
    name: 'Dark Swan Ballet Flats',
    img: '/img/Dark-Swan-Ballet-Flats.jpg',
    price: 180,
    description: 'Gothic Ballet flat snickers',
  },
  {
    id: '8',
    name: 'Goth Cowboy Boots',
    img: '/img/Goth-Cowboy-Boots.jpg',
    price: 310,
    description: 'Cowboy boots for your best look!',
  },
  {
    id: '9',
    name: 'Lets Dance Boots',
    img: '/img/Let_s-Dance-Boots.jpg',
    price: 350,
    description: 'Perfect purple shoes!',
  },
  {
    id: '10',
    name: 'Lock You Up Platform Shoes',
    img: '/img/LockU-Up-Platform-Shoes.jpg',
    price: 330,
    description: 'The tallest shoes ever!',
  },
  {
    id: '11',
    name: 'Lolli Purple',
    img: '/img/Lolli-Purple.jpg',
    price: 300,
    description: 'Beautiful lady sandals!',
  },
  {
    id: '12',
    name: 'Magic spell Platform shoes',
    img: '/img/Magic-spell-Platform-shoes.jpg',
    price: 200,
    description: 'Amazing Doll basic shoes',
  },
  {
    id: '13',
    name: 'Metal Night Boots',
    img: '/img/Metal-Night-Boots.jpg',
    price: 330,
    description: 'Beautiful tall boots!',
  },
  {
    id: '14',
    name: 'Naughty Girl Shoes',
    img: '/img/Naughty-Girl-Shoes.jpg',
    price: 400,
    description: 'Naughty doll shoes!',
  },
  {
    id: '15',
    name: 'Nighty Night Sandals',
    img: '/img/Nighty-Night-Sandals.jpg',
    price: 280,
    description: 'Elegant beautiful sandals',
  },
  {
    id: '16',
    name: 'Pandora KNEEHIGHBOOTS',
    img: '/img/Pandora-kneehighboots.jpg',
    price: 340,
    description: 'Crazy tall boots',
  },
  {
    id: '17',
    name: 'Poke You! Platform Shoes',
    img: '/img/PokeU-Platform-Shoes.jpg',
    price: 260,
    description: 'Nits Sandals-will work with any outfit!',
  },
  {
    id: '18',
    name: 'Siren Platform shoes',
    img: '/img/Siren-Platform-shoes.jpg',
    price: 290,
    description: 'The most gothic sandals',
  },
  {
    id: '19',
    name: 'Witchy Witch Boots',
    img: '/img/Witchy-Witch-Boots.jpg',
    price: 290,
    description: 'Elegant tall shoes, with best price',
  },
  {
    id: '20',
    name: 'Fairytale Pumps',
    img: '/img/Fairytale-Pumps.jpg',
    price: 215,
    description: 'Fancy gothic sandals',
  },
  {
    id: '21',
    name: 'Gothic Rock Shoes',
    img: '/img/shoes-gothic-rock.jpg',
    price: 190,
    description: 'Rock and Shoes Roll ',
  },
  {
    id: '22',
    name: 'Demonlicious Slippers',
    img: '/img/Demonlicious-Pink-Slippers.jpg',
    price: 110,
    description: 'Pink demons Slippers',
  },
  {
    id: '23',
    name: 'You Scared Slippers',
    img: '/img/U-Scared-Slippers.jpg',
    price: 90,
    description: 'Dont Be Scared!',
  },
  {
    id: '25',
    name: 'Halloween Slippers',
    img: '/img/Halloween-Slippers.jpg',
    price: 100,
    description: 'For your Halloween!',
  },
  {
    id: '26',
    name: 'Feed Me Slippers',
    img: '/img/Feed-Me-Slippers.jpg',
    price: 100,
    description: 'Yammy slippers',
  },
]

export default products
